services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin}"
      POSTGRES_DB: "${POSTGRES_DATABASE:-postgres}"
      TZ: "UTC"
    command: ["postgres", "-c", "timezone=UTC"]
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DATABASE:-postgres}",
        ]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - "${POSTGRES_VOLUME:-./.postgres}:/var/lib/postgresql/data"

  migrate:
    image: migrate/migrate:latest
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [
        "/bin/sh",
        "-c",
        "migrate \
        -path=/migrations \
        -database=postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-admin}@postgres:5432/${POSTGRES_DATABASE:-postgres}?sslmode=disable \
        up",
      ]
