namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;

    NEXT_PUBLIC_USE_EMULATOR: string;
    NEXT_PUBLIC_FIREBASE_EMULATOR_HOST: string;
    NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_PORT: string;
    NEXT_PUBLIC_FIRESTORE_EMULATOR_PORT: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_PORT: string;

    FIREBASE_SERVICE_ACCOUNT_PATH: string;
    GEMINI_API_KEY: string;
    GEMINI_LIVE_MODEL: string;
    PYTHON_ENGINE_URL: string;
  }
}
